bookings/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^packages/$', views.packages, name='packages'),
    url(r'^packages/item-(?P<item_id>\d+)/$', views.package_item, name='package-item'),
    url(r'^packages/book-package-(?P<package_id>\d+)/$', views.book_package, name='book-package'),
    url(r'^packages/booking-completed/$', views.booking_completed, name='booking-completed'),
    url(r'^packages/custom-package/$', views.create_package, name='custom-package'),
    url(r'^packages/custom-package/package-(?P<package_id>\d+)/$', views.create_package, name='customize-package'),
    url(r'^mybookings/$', views.mybookings, name='mybookings'),
]

iftsite/urls.py
from django.conf.urls import include, url

from iftsite.registration_backend import MyRegistrationView

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^atractions/$', views.atractions, name='atractions'),
    url(r'^post/(?P<id>[0-9]+)/$', views.post_detail, name='detail'),
    url(r'^auth/register/$', MyRegistrationView.as_view(), name='registration_register'),
]

iguazufallstour/urls.py
from django.conf.urls import include, url
from django.conf.urls import patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('iftsite.urls', namespace='iftsite')),
    url(r'', include('bookings.urls', namespace='bookings')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^contact/', include('contact_form.urls')),
]

admin.site.site_header = 'IFT Administration'

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

iftsite/models.py
# encoding: utf-8

from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse


TOURS_COUNTRIES = (
    ('AR', 'Argentina'),
    ('BR', 'Brazil'),
    ('PY', 'Paraguay'),
)


class HomeCarouselImage(models.Model):
    title = models.CharField(max_length=255)
    image = models.URLField()
    url = models.URLField(max_length=100, null=True, blank=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def admin_thumbnail(self):
        return u'<img src="%s" height=100/>' % (self.image)
    admin_thumbnail.short_description = 'Preview'
    admin_thumbnail.allow_tags = True


class Language(models.Model):
    name = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class Atraction(models.Model):
    country = models.CharField(max_length=2, choices=TOURS_COUNTRIES, default='AR')
    published = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __str__(self):
        return self.name


class PostCategory(models.Model):
    name = models.CharField(max_length=255)

    class Meta():
        verbose_name_plural = 'Post categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(PostCategory, default=1)
    published = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    text = HTMLField()

    def __str__(self):
        return self.title

    def get_absolut_url(self):
        return "/post/%s" %(self.id)

iftsite/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.contrib.auth.forms import UserCreationForm

from registration.users import UserModel, UsernameField

from bookings.models import Country


User = UserModel()

class RegisterForm(UserCreationForm):
    required_css_class = 'required'
    email = forms.EmailField(label=("E-mail"))
    username = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    first_name = forms.CharField(max_length=30, required=True, 
        label=_('First name'))
    last_name = forms.CharField(max_length=30, required=True,
        label=_('Last name'))
    address_line_1 = forms.CharField(max_length=100, required=True,
        label=_('Address line 1'))
    address_line_2 = forms.CharField(max_length=100, required=False,
        label=_('Address line 2'))
    city = forms.CharField(max_length=100, required=True,
        label=_('City'))
    state = forms.CharField(max_length=100, required=True,
        label=_('State'))
    country = forms.ModelChoiceField(
            queryset = Country.objects.all(),
            required = True,
            empty_label=None,
            label=_('Country'))

    tos = forms.BooleanField(widget=forms.CheckboxInput,
                             label = _('I have read and agree to the <a data-toggle="modal" data-target="#tos-modal">Terms of Service</a>'),
                             error_messages = {'required': _("You must agree to the terms to register")})

    class Meta:
        model = User
        fields = (UsernameField(), 'first_name', 'last_name','email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if len(email) > 30:
            raise forms.ValidationError('Maximum length of 30 characters.')
        self.cleaned_data['username'] = email
        if User.objects.filter(email__iexact=email):
            raise forms.ValidationError(_('This email address is already in use. Please supply a different email address.'))
        return email

    def clean_first_name(self):
        fname = self.cleaned_data['first_name']
        if len(fname) > 30:
            raise forms.ValidationError(_('Maximum length of 30 characters.'))
        return fname

    def clean_last_name(self):
        lname = self.cleaned_data['last_name']
        if len(lname) > 30:
            raise forms.ValidationError(_('Maximum length of 30 characters.'))
        return lname

iftsite/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from .models import HomeCarouselImage
from .models import Atraction
from .models import Post

# from .forms import RegisterForm

# Create your views here.
def home(request):
    carousel_slides = HomeCarouselImage.objects.filter(published=True)
    ar_atractions = Atraction.objects.filter(country='AR', published=True)
    br_atractions = Atraction.objects.filter(country='BR', published=True)
    py_atractions = Atraction.objects.filter(country='PY', published=True)

    context = {
        'carousel_slides': carousel_slides,
        'carousel_indicators': range(len(carousel_slides)),
        'ar_atractions': ar_atractions,
        'br_atractions': br_atractions,
        'py_atractions': py_atractions,
    }

    return render(request, 'iftsite/home.html', context)


def atractions(request):
    ar_atractions = Atraction.objects.filter(country='AR', published=True)
    br_atractions = Atraction.objects.filter(country='BR', published=True)
    py_atractions = Atraction.objects.filter(country='PY', published=True)

    context = {
        'ar_atractions': ar_atractions,
        'br_atractions': br_atractions,
        'py_atractions': py_atractions,
    }

    return render(request, 'iftsite/atractions.html', context)


def post_detail(request, id):
    post = get_object_or_404(Post, pk=id)

    context = {
        'post': post,
    }

    return render(request, 'iftsite/post.html', context)

iftsite/templates/iftsite/atractions.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% block title %} Atractions {% endblock %}
{% block content %}

{% trans "Brazil" as brazil %} 
{% trans "Argentina" as argentina %} 
{% trans "Paraguay" as paraguay %} 

  <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 blog-main">
          <div class="blog-header">
            <a class="anchor" id="top"></a>
            <h1 class="blog-title">{% trans "Atractions" %}</h1>
            <p class="lead blog-description">{% trans "Checkout the atractions in the tripoint." %}</p>
          </div>
          <div class="blog-post">
            <a class="anchor" id="br"></a>
            <h2 class="blog-post-title">{{ brazil }}</h2>
            <hr>
              {% for atraction in br_atractions %}
                <a class="anchor" id="{{ atraction.id }}"></a>
                <h3>{{ atraction.name }}</h3>
                {{ atraction.description | safe }}
              {% endfor %}
          </div>
          <div class="blog-post">
            <a class="anchor" id="ar"></a>
            <h2 class="blog-post-title">{{ argentina }}</h2>
            <hr>
              {% for atraction in ar_atractions %}
                <a class="anchor" id="{{ atraction.id }}"></a>
                <h3>{{ atraction.name }}</h3>
                {{ atraction.description | safe }}
              {% endfor %}
          </div>
          <div class="blog-post">
            <a class="anchor" id="py"></a>
            <h2 class="blog-post-title">{{ paraguay }}</h2>
            <hr>
              {% for atraction in py_atractions %}
                <a class="anchor" id="{{ atraction.id }}"></a>
                <h3>{{ atraction.name }}</h3>
                {{ atraction.description | safe }}
              {% endfor %}
          </div>
        </div><!-- /.blog-main -->
        <div class="col-md-2" role="complementary">
          <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix">
            <ul class="nav bs-docs-sidenav"  id="spy-sidebar">
              <li>
                <a href="#br">{{ brazil }}</a>
                <ul class="nav">
                  {% for atraction in br_atractions %}
                    <li><a href="#{{ atraction.id }}">{{ atraction.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li>
                <a href="#ar">{{ argentina }}</a>
                <ul class="nav">
                  {% for atraction in ar_atractions %}
                    <li><a href="#{{ atraction.id }}">{{ atraction.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li>
                <a href="#py">{{ paraguay }}</a>
                <ul class="nav">
                  {% for atraction in py_atractions %}
                    <li><a href="#{{ atraction.id }}">{{ atraction.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            </ul>
            <br>
            <a class="back-to-top" href="#top">
              {% trans "Back to top" %}
            </a>
          </nav>
        </div>
      </div><!-- /.row -->
    </div>}
{% endblock %}

iftsite/templates/iftsite/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <link rel="icon" href="../../favicon.ico">

  <title>IguazuFallsTour - {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "iftsite/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!--  Custom CSS-->
  <link href="{% static "iftsite/css/styles.css" %}" rel="stylesheet">
  <link href="{% static "iftsite/css/blog.css" %}" rel="stylesheet">
  <link href="{% static "iftsite/css/bootstrap-datepicker.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static "iftsite/js/main.js" %}"></script>
  <script src="{% static "iftsite/js/packages.js" %}"></script>
  <script src="{% static "iftsite/js/validator.min.js" %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  {% if LANGUAGE_CODE == 'pt-br' %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
  {% endif %}


  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body data-spy="scroll" data-target="#spy-sidebar" data-offset="140">
  <div id="wrapper">
    <div id="content">
      <!-- Navbar -->
      <div class="navbar navbar-default navbar-fixed-top" id="top-navbar">
        <div style="height:20px; background-color:#02A65A;"></div>
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'iftsite:home' %}"><span>Brand</span></a>
          </div>
          <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right" id="top-navbar">
              <li>
                <a>
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <input name="language" type="hidden" value="pt-br">
                    <input type="image" src="{% static "iftsite/media/br.png" %}" alt="Submit Form" />
                </form>
                </a>
              </li>
              <li>
                <a>
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <input name="language" type="hidden" value="en">
                    <input type="image" src="{% static "iftsite/media/gb.png" %}" alt="Submit Form" />
                </form>
                </a>
              </li>
              <li><a href="{% url 'iftsite:home' %}">Home</a></li>
              <li><a href="{% url 'bookings:packages' %}">{% trans "Packages" %}</a></li>
              <li><a href="{% url 'iftsite:atractions' %}">{% trans "Atractions" %}</a></li>
              <li><a href="{% url 'contact_form' %}">{% trans "Contact Us" %}</a></li>
              {% if request.user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Welcome" %} {{ request.user.first_name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'bookings:mybookings'%}">{% trans "My bookings" %}</a></li>
                    <li><a href="{% url 'auth_logout' %}">{% trans "Logout" %}</a></li>
                  </ul>
                </li>
              {% else %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Welcome" %} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'auth_login' %}">{% trans "Sign in" %}</a></li>
                    <li><a href="{% url 'registration_register' %}">{% trans "Register" %}</a></li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <!-- end Navbar -->


      <!-- Content -->
      <div class="offset-top">
      {% block content %}
      {% endblock %}
      </div>
      <!-- end Content -->
    </div>

    <div id="footer">
      <!-- Footer -->
      <footer class="section section-primary">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section">
                <div class="container">
                  <div class="row">
                    <div class="col-md-4 footer-links">
                      <h1><i class="fa fa-compass fa-2x"></i></h1>
                      <h2>{% trans "Travel Guide" %}</h2>
                      <ul class="footer-links">
                        {% for guide in guides %}
                          <li><a href="{{ guide.get_absolut_url }}"><h4>{{ guide.title }}</h4></a></li>
                        {% endfor %}
                      </ul>
                    </div>
                    <div class="col-md-4 footer-links">
                      <h1><i class="fa fa-wrench fa-2x"></i></h1>
                      <h2>{% trans "Utilities" %}</h2>
                      <ul class="footer-links">
                        {% for utility in utilities %}
                          <li><a href="{{ utility.get_absolut_url }}"><h4>{{ utility.title }}</h4></a></li>
                        {% endfor %}
                      </ul>
                    </div>
                    <div class="col-md-4 footer-links">
                      <h1><i class="fa fa-lightbulb-o fa-2x"></i></h1>
                      <h2>{% trans "Misc" %}</h2>
                      <ul class="footer-links">
                        {% for misc in miscs %}
                          <li><a href="{{ misc.get_absolut_url }}"><h4>{{ misc.title }}</h4></a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- end Footer -->
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src={% static "iftsite/bootstrap/js/bootstrap.min.js" %}></script>
</body>

</html>

iftsite/templates/iftsite/book_completed.html
{% extends "iftsite/base.html" %}
{% load i18n %}
{% block title %} booking completed {% endblock %}

{% block content %}
<div class="container offset-top">
    <div class="row">
      <div class="blog-post blog-main col-md-4 col-md-offset-4">
        <p>{% trans "The package has been booked, a email was sent to you with more details." %}</p>
      </div>
    </div>
</div>
{% endblock %}

iftsite/templates/iftsite/home.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% block title %}Home{% endblock %}
{% block content %}
  <div id="home-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      {% for i in carousel_indicators %}
        {% if forloop.first %}
          <li data-target="#home-carousel" class="active" data-slide-to="{{ i }}"></li>
        {% else %}
          <li data-target="#home-carousel" data-slide-to="{{ i }}"></li>
        {% endif %}
      {% endfor %}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      {% for slide in carousel_slides %}
        {% if forloop.first %}
          <div class="item active">
            <a href="{% if slide.url %} {{ slide.url }} {% else %} # {% endif %}">
            <img src="{{ slide.image }}">
            </a>
          </div>
        {% else %}
          <div class="item">
            <a href="{% if slide.url %} {{ slide.url }} {% else %} # {% endif %}">
            <img src="{{ slide.image }}" alt="...">
            </a>
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#home-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">{% trans "Previous" %}</span>
    </a>
    <a class="right carousel-control" href="#home-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">{% trans "Next" %}</span>
    </a>
  </div>

  <!-- Three countries -->
  <div class="section" id="home-main-section">
    <div class="container">
      <div class="row">
        <!-- Brazil -->
        <div class="col-md-4">
          <div class="panel country-panel">
            <div class="panel-heading-transparency"></div>
            <div class="panel-heading" role="tab">
              <a class="" role="button" data-toggle="collapse" href="#brazil-collapse-group" aria-expanded="true">
                <h2>{% trans "Brazil" %}</h2>
                <i class="fa fa-chevron-circle-down fa-2x"></i>
              </a>
            </div>
            <div id="brazil-collapse-group" class="panel-collapse collapse" role="tabpanel" aria-expanded="true">
              <div class="list-group">
                {% for atraction in br_atractions %}
                  <a href="/atractions/#{{ atraction.id }}" class="list-group-item">{{ atraction.name }}</a>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <!-- Argentina -->
        <div class="col-md-4">
          <div class="panel country-panel">
            <div class="panel-heading-transparency"></div>
            <div class="panel-heading" role="tab">
              <a class="" role="button" data-toggle="collapse" href="#argentina-collapse-group" aria-expanded="true">
                <h2>{% trans "Argentina" %}</h2>
                <i class="fa fa-chevron-circle-down fa-2x"></i>
              </a>
            </div>
            <div id="argentina-collapse-group" class="panel-collapse collapse" role="tabpanel" aria-expanded="true">
              <div class="list-group">
                {% for atraction in ar_atractions %}
                  <a href="/atractions/#{{ atraction.id }}" class="list-group-item">{{ atraction.name }}</a>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <!-- Paraguay -->
        <div class="col-md-4">
          <div class="panel country-panel">
            <div class="panel-heading-transparency"></div>
            <div class="panel-heading" role="tab">
              <a class="" role="button" data-toggle="collapse" href="#paraguay-collapse-group" aria-expanded="true">
                <h2>{% trans "Paraguay" %}</h2>
                <i class="fa fa-chevron-circle-down fa-2x"></i>
              </a>
            </div>
            <div id="paraguay-collapse-group" class="panel-collapse collapse" role="tabpanel"aria-expanded="true">
              <div class="list-group">
                {% for atraction in py_atractions %}
                  <a href="/atractions/#{{ atraction.id }}" class="list-group-item">{{ atraction.name }}</a>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

iftsite/templates/iftsite/post.html
{% extends 'iftsite/base.html' %}
{% block title %} Packages {% endblock %}
{% block content %}
<div class="container offset-top">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 blog-main">
        <div class="blog-header">
          <h1 class="blog-title">{{ post.title }}</h1>
        </div>
        <div class="blog-post">
          <hr>
          {{ post.text | safe }}
        </div>
      </div>
    </div>
 </div>
{% endblock %}