bookings/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^packages/$', views.packages, name='packages'),
    url(r'^packages/item-(?P<item_id>\d+)/$', views.package_item, name='package-item'),
    url(r'^packages/book-package-(?P<package_id>\d+)/$', views.book_package, name='book-package'),
    url(r'^packages/booking-completed/$', views.booking_completed, name='booking-completed'),
    url(r'^packages/custom-package/$', views.create_package, name='custom-package'),
    url(r'^packages/custom-package/package-(?P<package_id>\d+)/$', views.create_package, name='customize-package'),
    url(r'^mybookings/$', views.mybookings, name='mybookings'),
]

iftsite/urls.py
from django.conf.urls import include, url

from iftsite.registration_backend import MyRegistrationView

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^atractions/$', views.atractions, name='atractions'),
    url(r'^post/(?P<id>[0-9]+)/$', views.post_detail, name='detail'),
    url(r'^auth/register/$', MyRegistrationView.as_view(), name='registration_register'),
]

iguazufallstour/urls.py
from django.conf.urls import include, url
from django.conf.urls import patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('iftsite.urls', namespace='iftsite')),
    url(r'', include('bookings.urls', namespace='bookings')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^auth/', include('registration.backends.default.urls')),
    url(r'^contact/', include('contact_form.urls')),
]

admin.site.site_header = 'IFT Administration'

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

bookings/models.py
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ungettext
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist

from decimal import Decimal

from tinymce.models import HTMLField


PACKAGE_MODE = (
    ('SH', _('Shared')),
    ('PV', _('Private')),
)

PACKAGE_TYPE = (
    ('custom', 'Custom package'),
    ('offered', 'Offered package')
)

TOURS_COUNTRIES = (
    ('AR', 'Argentina'),
    ('BR', 'Brazil'),
    ('PY', 'Paraguay'),
)

CATEGORIES = (
    ('Hotel', 'Hotel'),
    ('Tour', 'Tour'),
    ('Extra', 'Extra'),
    ('Fee', 'Fee'),
)


class  Country(models.Model):

    name = models.CharField(max_length=255)

    class Meta:
    #     verbose_name = 'País'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class Item(models.Model):

    published = models.BooleanField(default=True)
    country = models.CharField(max_length=2, choices=TOURS_COUNTRIES, default='AR')
    included = models.BooleanField(default=True)
    title = models.CharField(max_length=255)
    info = HTMLField(blank=True)
    category = models.CharField(max_length=30, choices=CATEGORIES, default='Tour')

    def __str__(self):
        if self.included:
            return self.title
        return self.title + ' not included'

    def get_absolut_url(self):
        return reverse('bookings:package-item', args=(self.pk, ))

    def get_price(self, number_of_people=1):
        price = 0
        try:
            price = ItemPrice.objects.get(
                item=self,
                n_people=number_of_people
            )
            return price.price
        except ObjectDoesNotExist:
            return price


class ItemPrice(models.Model):

    item = models.ForeignKey(Item)
    n_people = models.IntegerField()
    price = models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):
        str = ungettext(
           'For %(count)d person',
           'For %(count)d people',
        self.n_people) % {
           'count': self.n_people,
        }
        return '{} U${}'.format(str, self.price)


class ItemMode(models.Model):

    item = models.ForeignKey(Item)
    mode = models.CharField(max_length=2, choices=PACKAGE_MODE)

    class Meta:
        unique_together =   ('item', 'mode')

    def __str__(self):
        str = self.item.title
        if self.item.included:
            str += ' ({})'.format(self.get_mode_display())
        else:
            str += ' not included'

        return str


class Package(models.Model):

    published = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    items = models.ManyToManyField(
        ItemMode,
        related_name='package_items',
        limit_choices_to=Q(item__category='Tour')|
            Q(item__category='Fee')|
            Q(item__category='Extra')|
            Q(item__category='Hotel')
    )
    profit_percent = models.IntegerField(blank=True, null=True, default=0)
    quoted_price = models.DecimalField(max_digits=19, decimal_places=2,
        blank=True, null=True)
    mode = models.CharField(max_length=2, choices=PACKAGE_MODE, default='PV')
    package_type = models.CharField(
        max_length=30,
        choices=PACKAGE_TYPE,
        default='offered'
    )

    def __str__(self):
        return self.name

    def format_profit(self):
        return str(self.profit_percent)+'%'

    def calculate_cost(self, number_of_people):
        cost = 0
        for item_mode in self.items.filter(item__included=True):
            try:
                item_price = ItemPrice.objects.get(
                    item=item_mode.item,
                    n_people=number_of_people,
                )
                cost += item_price.price
            except ObjectDoesNotExist:
                pass
        return cost

    def calculate_price(self, number_of_people):
        price = self.calculate_cost(number_of_people)
        return round(price * (1 + Decimal(self.profit_percent/100)),2)

    def get_formated_price(self, number_of_people):
        price = self.calculate_price(number_of_people)
        str = ungettext(
           'For %(count)d person',
           'For %(count)d people',
        number_of_people) % {
           'count': number_of_people,
        }
        if self.package_type == 'offered':
            return '{} U${}'.format(str, price)
        elif self.package_type == 'custom' and self.quoted_price:
            return '{} U${}'.format(str, self.quoted_price)
        else:
            return str

    def get_all_prices(self):
        """get avaliable prices for avaliable number of people"""
        show_if_equal = self.items.filter(item__included=True).count()
        prices = {}
        item_prices = []
        for item_mode in self.items.filter(item__included=True):
            item_prices.extend(ItemPrice.objects.filter(
                item=item_mode.item))
        for price in item_prices:
            try:
                prices[price.n_people]
            except KeyError:
                prices[price.n_people] = []
            prices[price.n_people].append(price)
        for n_people in list(prices):
            if len(prices[n_people]) == show_if_equal:
                prices[n_people] = self.get_formated_price(n_people)
            else:
                del prices[n_people]
        return prices


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.user.email


class ArrivalLocation(models.Model):

    location = models.CharField(max_length=100)

    def __str__(self):
        return self.location


class Booking(models.Model):

    STATUS = (
        ('New', _('New')),
        ('Viewed', _('Viewed')),
        ('Awaiting payment', _('Awaiting payment')),
        ('Confirmed', _('Confirmed')),
        ('Canceled', _('Canceled')),
        ('Closed', _('Closed'))
    )

    status = models.CharField(max_length=50, choices=STATUS, default='New')
    user = models.ForeignKey(User)
    package = models.ForeignKey(Package)
    number_of_people = models.IntegerField(default=1)
    booking_date = models.DateField()
    arrival_location = models.ForeignKey(ArrivalLocation)
    start_date = models.DateField()
    additional_info = models.TextField(null=True, blank=True)

    def user_name(self):
        return self.user.get_name()

    def user_email(self):
        return str(self.user.email)
    user_email.short_description = 'Email'

    def get_formated_price(self):
        return self.package.get_formated_price(self.number_of_people)

    def get_price(self):
        return self.package.calculate_price(self.number_of_people)

bookings/views.py
from datetime import date
from copy import deepcopy

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from .forms import BookPackageForm
from .forms import MakePackageForm

from .models import Package
from .models import ItemMode
from .models import Booking


def packages(request):
    if request.method == 'POST':
        package_id = request.POST['package_id']
        return HttpResponseRedirect(
            reverse('bookings:book-package', args=(package_id,))
        )
    else:
        packages_query = Package.objects.filter(published=True)
        packages = {}
        for package in packages_query:
            packages[package] = {}
            packages[package]['prices'] = package.get_all_prices()
            packages[package]['included'] = package.items.filter(
                item__included=True)
            packages[package]['excluded'] = package.items.filter(
                item__included=False)
        context = {
            'packages': packages,
        }
        return render(request, 'bookings/packages.html', context)


def package_item(request, item_id):
    item = get_object_or_404(ItemMode, pk=item_id)

    context = {
        'item': item,
    }
    return render(request, 'bookings/item.html', context)


def mybookings(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('auth_login'))

    bookings_query = Booking.objects.filter(user=request.user)
    bookings = {}

    for booking in bookings_query:
        bookings[booking] = {}
        bookings[booking]['package'] = booking.package
        bookings[booking]['included'] = booking.package.items.filter(
            item__included=True)
        bookings[booking]['excluded'] = booking.package.items.filter(
            item__included=False)

    context = {
        'bookings': bookings,
    }
    return render(request, 'bookings/mybookings.html', context)


def book_package(request, package_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('auth_login'))

    package = get_object_or_404(Package, pk=package_id)
    items = {
        'included': package.items.filter(item__included=True),
        'excluded': package.items.filter(item__included=False)
    }
    form = BookPackageForm(request.POST or None, request=request,
        user=request.user, package=package)

    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('bookings:booking-completed'))

    context = {
        'package': package,
        'items': items,
        'form': form,
    }

    return render(request, 'bookings/book_package.html', context)


def booking_completed(request):
    return render(request, 'bookings/booking_completed.html')


def create_package(request, package_id=None):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('auth_login'))

    package = None
    items = None
    if package_id:
        package = get_object_or_404(Package, pk=package_id)
        items = package.items.all()

    form = MakePackageForm(request.POST or None, request=request, items=items)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('bookings:booking-completed'))

    context = {
        'form': form,
    }
    return render(request, 'bookings/create_package.html', context)

bookings/templates/bookings/book_package.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}Book Package{% endblock %}
{% block content %}
<div class="container">
     <div class="row">
      <div class="blog-main col-md-8 col-md-offset-2">
        <div class="blog-header">
          <a class="anchor" id="top"></a>
          <h1 class="blog-title">{% trans "Book your visit" %}</h1>
          <p class="lead blog-description">{% trans "Book the package below." %}</p>
        </div>
        <div class="">
          <h2 class="blog-post-title">{{ package.name }}</h2>
          <p>{{ package.description }}</p>
          <h3>{% trans "What's included" %}:</h3>
          <ul>
          {% for item in items.included %}
            <li>
              <a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">
                {{ item }}
              </a>
            </li>
          {% endfor %}
          </ul>
          {% if items.excluded %}
            <h3>{% trans "What's not included:" %}</h3>
            <ul>
            {% for item in items.excluded %}
              <li>
                <a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">
                  {{ item.item.title }}
                </a>
              </li>
            {% endfor %}
            </ul>
          {% endif %}
        </div>
        <hr>
      </div>
    </div>
</div>
<div class="container">
  <div class="row">
    <div class="blog-main col-md-5 col-md-offset-2">
      {% crispy form %}
      <script type="text/javascript">
        $('.datepicker').datepicker({
          startDate: "today",
          autoclose: true,
          {% if LANGUAGE_CODE == 'pt-br' %}
          language: "pt-BR",
          {% endif %}
        })
      </script>
    </div>
  </div>
</div>
{% for item in items.included %}
<div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ item.item.title }}</h4>
      </div>
      <div class="modal-body blog-main">
        {{ item.item.info|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% for item in items.excluded %}
<div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ item.item.title }}</h4>
      </div>
      <div class="modal-body blog-main">
        {{ item.item.info|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
<div class="modal fade" id="tac-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ tac.title }}</h4>
      </div>
      <div class="modal-body blog-main">
        {{ tac.text|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bookings/templates/bookings/booking_completed.html
{% extends "iftsite/base.html" %}
{% load i18n %}
{% block title %} booking completed {% endblock %}

{% block content %}
<div class="container offset-top">
    <div class="row">
      <div class="blog-post blog-main col-md-4 col-md-offset-4">
        <p>{% trans "The package has been booked, a email was sent to you with more details, you can follow the status of your booking" %} <a href="/mybookings/">{% trans "here" %}</a>.</p>
      </div>
    </div>
</div>
{% endblock %}

bookings/templates/bookings/create_package.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %} Create your package {% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="blog-main col-md-8 col-md-offset-2">
        <div class="blog-header">
          <a class="anchor" id="top"></a>
          <h1 class="blog-title">{% trans "Packages" %}</h1>
          <p class="lead blog-description">{% trans "Make your own package, choose hotel and tours and get a quotation." %}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="blog-main col-md-5 col-md-offset-2">
        {% crispy form %}
        <script type="text/javascript">
          $('.datepicker').datepicker({
            startDate: "today",
            autoclose: true,
            {% if LANGUAGE_CODE == 'pt-br' %}
            language: "pt-BR",
            {% endif %}
          })
        </script>
      </div>
    </div>
  </div>
  <div class="modal fade" id="package-item-description-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="item-description-modal-title"></h4>
        </div>
        <div class="modal-body">
          <script>
            function resize_iframe(obj) {
              obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
            }
          </script>
          <iframe frameborder="0" id="package-item-description" onload="resize_iframe(this)"></iframe>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="tac-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ tac.title }}</h4>
      </div>
      <div class="modal-body blog-main">
        {{ tac.text|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

bookings/templates/bookings/email_admin_new_booking.html
{% spaceless %}
<p>New booking:</p>
<strong>User:</strong> {{ user.email }}
<br>
<strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}
<br><br>
<strong>Package:</strong> {{ package }}
<br>
What's included:
    <ul>
    {% for item in package.items.all %}
        {% if item.item.included %}
        <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% if package.package_type == 'offered' %}
What's not included:
    <ul>
    {% for item in package.items.all %}
        {% if not item.item.included %}
        <li>{{ item.item.title }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% endif %}
<strong>Numbe of people:</strong> {{ number_of_people }}
<br>
{% if package.package_type == 'offered' %}
<strong>Price:</strong> U${{ instance.get_price }}
<br>
{% endif %}
<strong>Booking date:</strong> {{ booking_date }}
<br>
<strong>Start date:</strong> {{ start_date }}
<br>
<strong>Arrival location:</strong> {{ arrival_location }}
<br>
{% if additional_info %}
<strong>Aditional information:</strong> {{ additional_info }}
<br>
{% endif %}
<br>
Iguazu Falls Tours
<br>
{{ site }}
{% endspaceless %}

bookings/templates/bookings/email_user_new_booking.html
{% load i18n %}
{% spaceless %}
<p>{% trans "Hello" %} {{ user.first_name }},</p>
<p>{% trans "Thank you for booking with us, this is your booking information" %}:</p>

<strong>{% trans "Package" %}:</strong> {{ package }}
<br>
{% trans "What's included" %}:
    <ul>
    {% for item in package.items.all %}
        {% if item.item.included %}
        <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% if package.package_type == 'offered' %}
{% trans "What's not included" %}:
    <ul>
    {% for item in package.items.all %}
        {% if not item.item.included %}
        <li>{{ item.item.title }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% endif %}
<strong>{% trans "Number of people" %}:</strong> {{ number_of_people }}
<br>
{% if package.package_type == 'offered' %}
<strong>{% trans "Price" %}:</strong> U${{ instance.get_price }}
<br>
{% endif %}
<strong>{% trans "Start date" %}:</strong> {{ start_date }}
<br>
<strong>{% trans "Arrival location" %}:</strong> {{ arrival_location }}
<br>
{% if additional_info %}
<strong>{% trans "Aditional information" %}:</strong> {{ additional_info }}
<br>
{% endif %}
<p>{% trans "You can follow the status of your booking" %} <a href="{{ site }}/mybookings/">{% trans "here" %}</a>.</p>
Iguazu Falls Tours
<br>
{{ site }}
{% endspaceless %}

bookings/templates/bookings/item.html
{% load staticfiles %}
<link href="{% static "iftsite/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "iftsite/css/blog.css" %}" rel="stylesheet">
<div class="blog-main">
    {{ item.info | safe }}
</div>

bookings/templates/bookings/mybookings.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% block title %}My Package{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
      <div class="blog-main col-md-8 col-md-offset-2">
        <div class="blog-header">
          <a class="anchor" id="top"></a>
          <h1 class="blog-title">{% trans "My Bookings" %}</h1>
          <p class="lead blog-description">{% trans "Your Bookings." %}</p>
        </div>
        {% if not bookings %}
          <p>{% trans "You haven't booked any package yet. Check out our packages" %} <a href="{% url 'bookings:packages' %}">{% trans "here" %}!</a></p>
        {% endif %}
        {% for booking, properties in bookings.items %}
          <div>
            <h2 class="blog-post-title">{{ properties.package.name }}</h2>
            {% if properties.package.description %}
              <p>{{ properties.package.description }}</p>
            {% endif %}
            <h3>{% trans "What's included" %}:</h3>
            <ul>
              {% for item in properties.included %}
                  <li><a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">{{ item }}</a></li>
              {% endfor %}
            </ul>
            {% if properties.excluded %}
            <h3>{% trans "What's not included" %}:</h3>
            <ul>
              {% for item in properties.excluded %}
                  <li><a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">{{ item }}</a></li>
              {% endfor %}
            </ul>
            {% endif %}
            <p>{{ booking.get_formated_price }}</p>
            <p>{% trans "Start date" %}: {{ booking.start_date }}</p>
            <p>{% trans "Arrival at" %}: {{ booking.arrival_location }}</p>
            <p>Status: {{ booking.get_status_display }}</p>
          </div>
          <hr>
          {% for item in properties.included %}
          <div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">{{ item.item.title }}</h4>
                </div>
                <div class="modal-body blog-main">
                  {{ item.item.info|safe }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% for item in properties.excluded %}
            <div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">{{ item.item.title }}</h4>
                </div>
                <div class="modal-body blog-main">
                  {{ item.item.info|safe }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

bookings/templates/bookings/packages.html
{% extends 'iftsite/base.html' %}
{% load i18n %}
{% block title %} Packages {% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="blog-main col-md-8 col-md-offset-2">
        <div class="blog-header">
          <a class="anchor" id="top"></a>
          <h1 class="blog-title">{% trans "Packages" %}</h1>
          <p class="lead blog-description">{% trans "Checkout our packages." %}</p>
        </div>
        <div class="jumbotron blog-post">
          <h1>{% trans "Make Your Custom Package!" %}</h1>
          <p>{% trans "Choose hotel and tours. Price on request." %}</p>
          <p><a class="btn btn-success btn-lg" href="{% url 'bookings:custom-package' %}" role="button">{% trans "Learn more" %}</a></p>
        </div>
        <hr>
        {% for package, properties in packages.items %}
          <div>
            <h2 class="blog-post-title">{{ package.name }}</h2>
            <p>{{ package.description }}</p>
            <h3>{% trans "What's included" %}:</h3>
            <ul>
            {% for item in properties.included %}
                <li><a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">{{ item }}</a></li>
            {% endfor %}
            </ul>
            {% if properties.excluded %}
              <h3>{% trans "What's not included" %}:</h3>
              <ul>
              {% for item in properties.excluded %}
                  <li><a style="cursor:pointer;" data-toggle="modal" data-target="#item-{{ item.pk }}-info-modal">{{ item.item.title }}</a></li>
              {% endfor %}
              </ul>
              <h3>{% trans "Prices:" %}</h3>
              <ul>
              {% for n_people, price in properties.prices.items %}
              <li>{{ price }}</li>
              {% endfor %}
              </ul>
            {% endif %}
            <form id="package-{{ package.pk }}-form"  method="post">
              {% csrf_token %}
              <input type="hidden" name="package_id" value="{{ package.pk }}">
              <button class="btn btn-success" type="submit" form="package-{{ package.pk }}-form">{% trans "Book this package" %}</button>
            </form>
          </div>
          <hr>
          {% for item in properties.included %}
          <div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">{{ item.item.title }}</h4>
                </div>
                <div class="modal-body blog-main">
                  {{ item.item.info|safe }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% for item in properties.excluded %}
            <div class="modal fade" id="item-{{ item.pk }}-info-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">{{ item.item.title }}</h4>
                </div>
                <div class="modal-body blog-main">
                  {{ item.item.info|safe }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}